baseURL = "https://linct.xyz/"
languageCode = "en-us"
paginate = 5.0
title = "Site"
theme = "PaperMod"

# æ”¯æŒæœç´¢
[outputs]
  home = [
    "HTML",
    "RSS",
    "JSON"
  ]

[params]
  description = "my site"
  author = "linct"
  defaultTheme = "auto"
  ShowReadingTime = true # å±•ç¤ºé˜…è¯»æ—¶é—´
  ShowShareButtons = true # å±•ç¤ºåˆ†äº«æŒ‰é’®

  # é¦–é¡µä¿¡æ¯ 
  [params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = """
      Welcome to my blog dsa
    Welcome to my blog dsa
    """
  
  # è”ç³»æŒ‰é’®
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/"

  [[params.socialIcons]]
    name = "stackoverflow"
    url = "https://stackoverflow.com"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

  [[params.socialIcons]]
    name = "buymeacoffee"
    url = "https://github.com/"

    
  # æœç´¢è®¾ç½®
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0.0
    distance = 1000.0
    threshold = 0.4
    minMatchCharLength = 0.0
    keys = [
      "title",
      "permalink",
      "summary",
      "content"
    ]
    
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 10.0

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 10.0

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 10.0
