baseURL = "https://linct.xyz/"
languageCode = "en-us"
paginate = 5.0
title = "Site"
theme = "PaperMod"

# è®¾ç½®æ–‡æ¡£ https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-variables/#site-variables-under-params
[params]
  title = "title"
  description = "my description"
  author = "linct"
  defaultTheme = "auto"
  ShowReadingTime = true # å±•ç¤ºé˜…è¯»æ—¶é—´
  ShowShareButtons = true # å±•ç¤ºåˆ†äº«æŒ‰é’®
  comments = true
  enableGitalk = true


  [params.Gitalk]
    clientID = "b7233ea49aef7982eb5b" # Your client ID
    clientSecret = "89cb07e16efecf74de7e423ad0306f0129a4356d" # Your client secret
    repo = "https://github.com/linct96/git-talk.git" # The repo to store comments
    owner = "linct96" # Your GitHub ID
    admin= "linct96" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 10 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

  # é¦–é¡µä¿¡æ¯ 
  [params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = """
      Welcome to my blog dsa
    Welcome to my blog dsa
    Welcome to my blog dsa
    Welcome to my blog dsa
    """
  
  # è”ç³»æŒ‰é’®
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/"

  [[params.socialIcons]]
    name = "stackoverflow"
    url = "https://stackoverflow.com"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

  [[params.socialIcons]]
    name = "buymeacoffee"
    url = "https://github.com/"

    
  # æœç´¢è®¾ç½®
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0.0
    distance = 1000.0
    threshold = 0.4
    minMatchCharLength = 0.0
    keys = [
      "title",
      "permalink",
      "summary",
      "content"
    ]
    
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 10.0

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 10.0

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 10.0

# æ”¯æŒæœç´¢
[outputs]
  home = [
    "HTML",
    "RSS",
    "JSON"
  ]